target/A/1.txt: source/A/1.png
  mkdir -p $(dir $@)
  touch $$@

target/A/2.txt: source/A/2.png
  mkdir -p $(dir $@)
  touch $$@

target/A/3.txt: source/A/3.png
  mkdir -p $(dir $@)
  touch $$@

target/B/1.txt: source/B/1.png
  mkdir -p $(dir $@)
  touch $$@

target/B/2.txt: source/B/2.png
  mkdir -p $(dir $@)
  touch $$@

target/B/3.txt: source/B/3.png
  mkdir -p $(dir $@)
  touch $$@

target/C/1.txt: source/C/1.png
  mkdir -p $(dir $@)
  touch $$@

target/C/2.txt: source/C/2.png
  mkdir -p $(dir $@)
  touch $$@

target/C/3.txt: source/C/3.png
  mkdir -p $(dir $@)
  touch $$@
